[package]
name = "assembler"
version = "0.1.0"
edition = "2021"
authors = ["Kyle Gagnon"]

[dependencies]
lazy_static = "1.4.0"
bitflags = "1.2.1"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
nom = "7.1.3"
clap = { version = "4.3.19", features = ["derive"] }
thiserror = "1.0.44"
serde = { version = "1.0.180", features = ["derive"] }
serde_json = { version = "1.0.104" }
nes_lib = { path = "../../nes_lib" }